stages:
  - precommit
  - test
  - deploy

precommit:
  stage: precommit
  image: python:3.10
  before_script:
    - pip install pre-commit pylint
  script:
    - pre-commit run --all-files

test:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
    - python manage.py migrate
  script:
    - python manage.py test

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - ssh deboraa308@ssh.pythonanywhere.com "
        cd /home/deboraa308/toDoList/toDoList_ProjetoManutencaoSoftware-5 &&
        git pull origin main &&
        pip install -r requirements.txt &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        touch /var/www/deboraa308_pythonanywhere_com_wsgi.py
      "
