repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--init-hook", "import sys; sys.path.insert(0, '.')"]
        files: ^core/(models|views|serializers)\.py$
